services:
    # uwsgiBotApp:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    #     image: vaultboy3922/webapp:latest
    #     ports:
    #         - "80:80"
    #     # volumes:
    #     #     - ./src/.env: /app/.env
    #     env_file: "./.env"

    discordBot:
        image: vaultboy3922/bot:latest
        env_file: "./.env"
=======
    #     image: vaultboy3922/webapp:0.3b1
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./config.yml:./config.yml

    discordBot:
        image: vaultboy3922/bot:0.3a1
        volumes:
            - ./config.yml:/config.yml
>>>>>>> Stashed changes
=======
    #     image: vaultboy3922/webapp:0.3b1
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./config.yml:./config.yml

    discordBot:
        image: vaultboy3922/bot:0.3a1
        volumes:
            - ./config.yml:/config.yml
>>>>>>> Stashed changes
