FROM python:3.14.3-alpine3.23

ADD src/textsCogs.py .
ADD src/ownerCogs.py .
ADD src/main.py .
ADD src/NocoClass.py .
ADD src/TwilioClass.py .
ADD src/config.py .
RUN pip install twilio rich requests discord.py pyyaml typing pydantic

CMD ["python", "main.py"]
# CMD ["python", "uwsgi --socket 0.0.0.0:80 --protocol=http -w wsgi:app  "]